from fastapi import APIRouter, Depends, HTTPException, status, File, UploadFile, Request,Form
from sqlalchemy.orm import Session
from pydantic import BaseModel, EmailStr, field_validator
import random,string
from datetime import datetime, timedelta
from jose import JWTError, jwt

#We import the database i am going to use, with a session function.
from Models.Database import Group,GroupMember,Credentials,UserProfile,ChatMessages, get_db
from Routes.Authentication import get_current_user

router = APIRouter(prefix="/api/groups", tags=["Groups"])

class RoomCodeCollide(Exception):
    """Exception raised because room code already exists."""
    def __init__(self) -> None:
        super().__init__("Room code generated by system already exists.")

class joinRoomSchema(BaseModel):
    joincode: str
    joining_by_uuid: str

class createRoomSchema(BaseModel):
    roomname: str
    created_by_uuid: str

class leaveRoomSchema(BaseModel):
    group_id: str
    target_uuid: str
    role: str

class dissolveRoomSchema(BaseModel):
    groupcode: str
    target_uuid: str

def createRoomCode(size=10,chars=string.ascii_uppercase + string.digits):
#This function is used to create an unique roomcode.
#Choice function select random element from non-spaced seq. and range generates 6 items using string passed.
#string.ascii_uppercase generates all letters A-Z
#string.digits generates all numbers 0-9
#chars combine both of them and creates a long string.
#random.SystemRandom() uses OS builtin cryptographic source.
# . choice() picks one character from the string passes.
# for loop iterates for N times. hence, creating unique code.
    roomcode = ''.join(random.SystemRandom().choice(chars) for _ in range(size))

    return roomcode

@router.post("/create")
def createRoom(room: createRoomSchema, db: Session = Depends(get_db), current_user: dict = Depends(get_current_user)):
    
    # 1. Validate the user
    if room.created_by_uuid != current_user['user_id']:
        raise HTTPException(status_code=status.HTTP_403_FORBIDDEN, detail="Invalid operation to create a room.")
    
    # 2. Generate a UNIQUE room code
    while True:
        ROOMCODE = createRoomCode()
        existsroomcode = db.query(Group).filter(Group.invitecode == ROOMCODE).first()
        if not existsroomcode:
            break 
            
    # 3. Create the Group
    entry = Group(
        group_name=room.roomname,
        created_by_id=room.created_by_uuid,
        invitecode=ROOMCODE
    )
    db.add(entry)
    db.commit()
    db.refresh(entry)

    # 4. Add the creator as the first GroupMember
    member = GroupMember(
        group_id=ROOMCODE,              
        user_id=entry.created_by_id,
        is_admin="admin"                
    )
    db.add(member)
    db.commit()
    
    record = db.query(GroupMember).filter(GroupMember.user_id == room.created_by_uuid).first()
    
    if not record:
        raise HTTPException(status_code=500, detail="Failed to retrieve room data after creation.")
        
    # Construct the dictionary directly
    room_data = {
        "group_id": record.group_id,
        "room_code": entry.invitecode,
        "role": record.is_admin,
        "Groupname":room.roomname,
        "RoomCodeVisibility":entry.can_see_invite_code
    }
    #Can see invite code attribute is global constriant
    return room_data
    
@router.post("/join")
def joinRoom(room: joinRoomSchema, db: Session = Depends(get_db), current_user: dict = Depends(get_current_user)):
    try:
        # 1. Validate ownership
        if room.joining_by_uuid != current_user['user_id']:
            raise HTTPException(status_code=status.HTTP_403_FORBIDDEN, detail="There was an error joining a room.")

        # 2. Find room by invite code
        record = db.query(Group).filter(Group.invitecode == room.joincode).first()

        if not record:
            raise HTTPException(status_code=404, detail="Room not found. Check the invite code.")

        # 3. Check not already a member
        already_member = db.query(GroupMember).filter(
            GroupMember.group_id == record.invitecode,
            GroupMember.user_id == room.joining_by_uuid
        ).first()

        if already_member:
            raise HTTPException(status_code=400, detail="You are already a member of this room.")

        # 4. Add as member
        member = GroupMember(
            group_id=record.invitecode,
            user_id=room.joining_by_uuid,
            is_admin="member"
        )
        db.add(member)
        db.commit()
        db.refresh(member)

        #Get username:
        
        username = db.query(Credentials).filter(Credentials.unique_user_id == room.joining_by_uuid).first()

        notif = None

        if username and username:
            print("Username found while leaving:",username)
            #Add a notification:
            notif = ChatMessages(group_id=member.group_id,
                             sender_id=room.joining_by_uuid,
                             message=f"{username.first_name} {username.last_name} has joined the room. Welcome!",
                             timestamp=datetime.now(),
                             msgtype="notification")
            db.add(notif)
            db.commit()
            db.refresh(notif)

        return {
            "group_id": member.group_id,
            "room_code": record.invitecode,
            "role": member.is_admin,
            "CanExportHistory":member.can_export_history,
            "CanChat":member.can_chat,
            "CanUpdateCalendar":member.can_update_calendar,
        }

    except HTTPException as e:
        db.rollback()
        print(e)
        raise
    except Exception as e:
        db.rollback()
        print(f"Join room error: {e}")
        raise HTTPException(status_code=500, detail="Internal server error.")

@router.post("/leave")
def leaveRoom(room: leaveRoomSchema, db: Session = Depends(get_db),current_user: dict = Depends(get_current_user)):
    try:
        # 1. Validate the user
        if room.target_uuid != current_user['user_id']:
            raise HTTPException(status_code=status.HTTP_403_FORBIDDEN, detail="You have not joined a room yet.")
        
        # Admin cannot leave.
        record = db.query(GroupMember).filter(GroupMember.is_admin == "admin",GroupMember.user_id == room.target_uuid).first()
        
        if record:
            print("Record admin: ",record.is_admin)
            return {"adminError":"Admins cannot leave the room. Dissolve the room instead."}

        #Get username:
        username = db.query(Credentials).filter(Credentials.unique_user_id == room.target_uuid).first()

        notif = None
        print("--------------------------------")
        if username:
            print("Username found while leaving:",username)

            #Add a notification:
            notif = ChatMessages(group_id=room.group_id,
                             sender_id=room.target_uuid,
                             message=f"{username.first_name} {username.last_name} has left the room.",
                             timestamp=datetime.now(),
                             msgtype="notification")
            
            db.add(notif)
            db.commit()
            db.refresh(notif)
        else:
            print("Username found while leaving:",username)
        #Delete
        user = db.query(GroupMember).filter(GroupMember.user_id == room.target_uuid, GroupMember.group_id == room.group_id).delete()

        db.commit()

        return {"message":"user removed from the room."}
    
    except Exception as e:
        print("error:",e)
        db.rollback()
        raise

@router.post("/dissolve")
def dissolveRoom(room: dissolveRoomSchema, db: Session = Depends(get_db), current_user: dict = Depends(get_current_user)):
    try:
        # 1. Validate the user making the request
        if room.target_uuid != current_user['user_id']:
            raise HTTPException(status_code=status.HTTP_403_FORBIDDEN, detail="Unauthorized operation.")
        
        # 2. Verify the user is an admin of this specific group
        admin_record = db.query(GroupMember).filter(
            GroupMember.user_id == room.target_uuid, 
            GroupMember.group_id == room.groupcode,
            GroupMember.is_admin == "admin"
        ).first()
        
        if not admin_record:
            raise HTTPException(status_code=status.HTTP_403_FORBIDDEN, detail="Only admins can dissolve the room.")
        

        # 3. Clean up all members from the group first to prevent Foreign Key constraint blocks
        db.query(GroupMember).filter(GroupMember.group_id == room.groupcode).delete()
        
        # 4. Delete the group itself
        db.query(Group).filter(Group.invitecode == room.groupcode).delete()
        
        db.commit()
        
        return {"message": "Room dissolved successfully."}
    
    except HTTPException:
        db.rollback()
        raise
    except Exception as e:
        print("error:", e)
        db.rollback()
        raise HTTPException(status_code=status.HTTP_500_INTERNAL_SERVER_ERROR, detail="Failed to dissolve room")
    
@router.get("/getroomcode")
def getRoomCode(db: Session = Depends(get_db),current_user: dict = Depends(get_current_user)):
    
    if not current_user['user_id']:
        raise HTTPException(status_code=status.HTTP_500_INTERNAL_SERVER_ERROR, detail="Room code not found. Try logging in again.")
    
    #Since user must be in room to get roomcode, we do not need to put a security check here.
    try:
        user_id = current_user['user_id']

        usergrpdata = db.query(GroupMember).filter(GroupMember.user_id == user_id).first()

        if not usergrpdata:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="User does not seem to be in a group.")
        
        return {
        "message": "Group id found.", 
        "room_code": usergrpdata.group_id
        }
    except HTTPException as e:
        db.rollback()
        raise

@router.get("/members/{groupcode}")
def getGroupMembers(groupcode: str, db: Session = Depends(get_db), current_user: dict = Depends(get_current_user)):
    try:
        # 1. Verify the user requesting the list is actually in this group
        user_in_group = db.query(GroupMember).filter(
            GroupMember.group_id == groupcode,
            GroupMember.user_id == current_user['user_id']
        ).first()

        if not user_in_group:
            raise HTTPException(status_code=status.HTTP_403_FORBIDDEN, detail="You are not a member of this room.")

        # 2. INLINED QUERY: Join GroupMember, Credentials, and UserProfile to get the full UI data
        members_data = db.query(
            GroupMember.is_admin,
            Credentials.first_name,
            Credentials.last_name,
            Credentials.email,
            Credentials.unique_user_id,
            UserProfile.pfp_path
        ).join(
            Credentials, GroupMember.user_id == Credentials.unique_user_id
        ).join(
            UserProfile, GroupMember.user_id == UserProfile.unique_user_id
        ).filter(
            GroupMember.group_id == groupcode
        ).all()
        
        # 3. Construct the response
        member_data = []
        for member in members_data:
            member_data.append({
                "first_name": member.first_name,
                "last_name": member.last_name,
                "email": member.email,
                "role": member.is_admin,
                "user_id":member.unique_user_id,
                "pfp_path": member.pfp_path
            })

        return {"members": member_data}

    except HTTPException:
        raise
    except Exception as e:
        print("Fetch members error:", e)
        raise HTTPException(status_code=500, detail="Failed to fetch group members.")