import { useState, useEffect } from "react";
import PageBreadcrumb from "../../components/common/PageBreadCrumb";
import PageMeta from "../../components/common/PageMeta";
import Avatar from "../../components/ui/avatar/Avatar";
import Button from "../../components/ui/button/Button";
import Badge from "../../components/ui/badge/Badge";
import { useAuth } from "../../context/AuthContext";
import {
  Table,
  TableBody,
  TableCell,
  TableHeader,
  TableRow,
} from "../../components/ui/table"; // Adjust path if your table components are located elsewhere

// Define strict typing for the incoming data
interface Member {
  first_name: string;
  last_name: string;
  email: string;
  role: string;
  pfp_path: string;
}

export default function Members() {
  const [members, setMembers] = useState<Member[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  
  const { isAdmin } = useAuth(); // Determine if they see management actions
  const VITE_ROUTE_API_KEY = import.meta.env.VITE_ROUTE_API_KEY;

  useEffect(() => {
    const fetchMembers = async () => {
      try {
        const currentRoom = JSON.parse(localStorage.getItem('currentRoom') || '{}');
        const token = localStorage.getItem('access_token'); 
        
        
        // Safely extract the exact key generated by your backend
        const safeGroupCode = currentRoom.Groupid || "";
        console.log("Group code fetched: ",safeGroupCode);
        console.log("Current grp: ",currentRoom); 
        if (!safeGroupCode) {
          setError("No active room found. Please join a room first.");
          setIsLoading(false);
          return;
        }

        if (!token) {
          setError("Authentication token missing. Please log in again.");
          setIsLoading(false);
          return;
        }

        const response = await fetch(`${VITE_ROUTE_API_KEY}/groups/members/${safeGroupCode}`, {
          method: 'GET',
          headers: {
            'Authorization': `Bearer ${token}`
          }
        });

        const data = await response.json();

        if (response.ok) {
          setMembers(data.members);
        } else {
          setError(data.detail || "Failed to load members.");
        }
      } catch (err) {
        console.error(err);
        setError("An unexpected error occurred while fetching members.");
      } finally {
        setIsLoading(false);
      }
    };

    fetchMembers();
  }, [VITE_ROUTE_API_KEY]);

  return (
    <div>
      <PageMeta
        title="Members | Group Expense Tracker"
        description="View and manage group members in Group Expense Tracker."
      />
      <PageBreadcrumb pageTitle="Members" />
      
      <div className="space-y-6">
        {/* Header Information */}
        <div className="rounded-2xl border border-gray-200 bg-white px-5 py-7 dark:border-gray-800 dark:bg-white/[0.03] xl:px-10">
          <h3 className="mb-2 font-semibold text-gray-800 text-theme-xl dark:text-white/90 sm:text-2xl">
            Group Members
          </h3>
          <p className="text-sm text-gray-500 dark:text-gray-400 sm:text-base">
            Browse the group member list and manage user access.
          </p>
        </div>

        {/* In-UI Error Display instead of Alerts */}
        {error && (
          <div className="p-4 rounded-lg bg-error-50 border border-error-200 text-error-600 dark:bg-error-500/10 dark:border-error-500/20 dark:text-error-400 text-sm text-center">
            {error}
          </div>
        )}

        {/* Loading State */}
        {isLoading && !error && (
          <div className="text-center text-gray-500 dark:text-gray-400 py-10">
            Loading members...
          </div>
        )}

        {/* Data Table */}
        {!isLoading && !error && members.length > 0 && (
          <div className="overflow-hidden rounded-xl border border-gray-200 bg-white dark:border-white/[0.05] dark:bg-white/[0.03]">
            <div className="max-w-full overflow-x-auto">
              <Table>
                {/* Table Header */}
                <TableHeader className="border-b border-gray-100 dark:border-white/[0.05]">
                  <TableRow>
                    <TableCell isHeader className="px-5 py-3 font-medium text-gray-500 text-start text-theme-xs dark:text-gray-400">
                      Member
                    </TableCell>
                    <TableCell isHeader className="px-5 py-3 font-medium text-gray-500 text-start text-theme-xs dark:text-gray-400">
                      Email
                    </TableCell>
                    <TableCell isHeader className="px-5 py-3 font-medium text-gray-500 text-start text-theme-xs dark:text-gray-400">
                      Role
                    </TableCell>
                    <TableCell isHeader className="px-5 py-3 font-medium text-gray-500 text-center text-theme-xs dark:text-gray-400">
                      Actions
                    </TableCell>
                  </TableRow>
                </TableHeader>

                {/* Table Body */}
                <TableBody className="divide-y divide-gray-100 dark:divide-white/[0.05]">
                  {members.map((member, index) => (
                    <TableRow key={index}>
                      <TableCell className="px-5 py-4 sm:px-6 text-start">
                        <div className="flex items-center gap-3">
                          {/* Use your Avatar component for the profile picture */}
                          <Avatar src={member.pfp_path} size="small" />
                          <div>
                            <span className="block font-medium text-gray-800 text-theme-sm dark:text-white/90">
                              {member.first_name} {member.last_name}
                            </span>
                          </div>
                        </div>
                      </TableCell>
                      
                      <TableCell className="px-4 py-3 text-gray-500 text-start text-theme-sm dark:text-gray-400">
                        {member.email}
                      </TableCell>
                      
                      <TableCell className="px-4 py-3 text-gray-500 text-start text-theme-sm dark:text-gray-400">
                        <Badge
                          size="sm"
                          color={member.role === "admin" ? "success" : "light"}
                        >
                          {member.role.charAt(0).toUpperCase() + member.role.slice(1)}
                        </Badge>
                      </TableCell>
                      
                      <TableCell className="px-4 py-3 text-gray-500 text-center text-theme-sm dark:text-gray-400">
                        {/* Placeholder for future admin management features (e.g., Kick Member, Make Admin) */}
                        <div className="flex items-center justify-center gap-2">
                          {isAdmin && member.role !== 'admin' ? (
                            <Button size="sm" variant="outline">
                              Manage
                            </Button>
                          ) : (
                            <span className="text-gray-400 text-xs">-</span>
                          )}
                        </div>
                      </TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            </div>
          </div>
        )}

        {/* Empty State */}
        {!isLoading && !error && members.length === 0 && (
          <div className="text-center text-gray-500 dark:text-gray-400 py-10">
            No members found in this group.
          </div>
        )}
      </div>
    </div>
  );
}