//This file is entirely generated by Gemini pro. I do not understand any of this animation stuff :)
//My original work is the design,workflow and logic of entire project.
import React, { useState, useRef } from "react";
import { DotLottieReact } from "@lottiefiles/dotlottie-react";
import { Modal } from "../ui/modal";
import Button from "../ui/button/Button";

// Import your highly optimized Lottie asset
import GibliTribute from "../../assets/animation/GibliTribute.lottie";

interface CreditsProps {
  isOpen: boolean;
  onClose: () => void;
}

export default function Credits({ isOpen, onClose }: CreditsProps) {
  // Coordinate tracking for the draggable animation
  const [position, setPosition] = useState({ x: 0, y: -50 });
  const [isDragging, setIsDragging] = useState(false);
  const dragStartPos = useRef({ x: 0, y: 0 });

  const handlePointerDown = (e: React.PointerEvent<HTMLDivElement>) => {
    setIsDragging(true);
    // Capture the exact pixel the user grabbed relative to the element's current position
    dragStartPos.current = {
      x: e.clientX - position.x,
      y: e.clientY - position.y,
    };
    
    // Capture the pointer so dragging works even if the mouse moves off the element fast
    (e.target as HTMLDivElement).setPointerCapture(e.pointerId);
  };

  const handlePointerMove = (e: React.PointerEvent<HTMLDivElement>) => {
    if (isDragging) {
      // Calculate the new coordinates
      const newX = e.clientX - dragStartPos.current.x;
      const newY = e.clientY - dragStartPos.current.y;
      
      setPosition({ x: newX, y: newY });
    }
  };

  const handlePointerUp = (e: React.PointerEvent<HTMLDivElement>) => {
    setIsDragging(false);
    (e.target as HTMLDivElement).releasePointerCapture(e.pointerId);
  };

  return (
    <Modal 
      isOpen={isOpen} 
      onClose={onClose} 
      className="max-w-[900px] overflow-hidden bg-white dark:bg-gray-900"
    >
      {/* The main relative container that restricts the draggable area */}
      <div className="relative flex flex-col items-center justify-center p-8 min-h-[500px]">
        
        {/* Background Credits Text (Centered) */}
        <div className="z-10 flex flex-col items-center justify-center text-center pointer-events-none select-none">
          <h2 className="mb-4 text-3xl font-bold tracking-tight text-gray-800 dark:text-white">
            Group Expense Tracker
          </h2>
          
          <p className="max-w-md mb-8 text-gray-500 leading-relaxed dark:text-gray-400">
            A full-stack application engineered for seamless financial collaboration. 
            Built with modern React, highly optimized FastAPI endpoints, and secure PostgreSQL databases.
          </p>

          <div className="w-full max-w-sm pt-6 border-t border-gray-200 dark:border-gray-800">
            <p className="text-xs tracking-widest text-gray-400 uppercase mb-2">
              Lead Architecture & Development
            </p>
            <p className="text-lg font-medium text-gray-800 dark:text-white">
              Aziz Shahiwala
            </p>
            <p className="mt-2 text-sm text-gray-500">
              Foundational principles honed at GLS FCAIT. Thankyou for reading!
            </p>
          </div>
        </div>

        {/* The Draggable Lottie Overlay */}
        <div 
          className="absolute z-20 w-48 h-48 cursor-grab active:cursor-grabbing touch-none"
          style={{ 
            transform: `translate(${position.x}px, ${position.y}px)`,
            // Add a slight transition only when NOT dragging so it snaps back smoothly if needed later
            transition: isDragging ? "none" : "transform 0.1s ease-out" 
          }}
          onPointerDown={handlePointerDown}
          onPointerMove={handlePointerMove}
          onPointerUp={handlePointerUp}
          onPointerCancel={handlePointerUp}
        >
          <DotLottieReact
            src={GibliTribute}
            loop
            autoplay
            className="w-full h-full drop-shadow-2xl pointer-events-none"
          />
        </div>

        {/* Footer Actions */}
        <div className="absolute bottom-6 w-full px-8 z-30 flex justify-center">
            <Button 
                variant="outline" 
                size="sm" 
                onClick={onClose}
                className="w-full max-w-[250px]"
            >
                Close Credits
            </Button>
        </div>
      </div>
    </Modal>
  );
}
